Repository inviqa/harness-go, pull requests merged in 2021-06, with the labels that each got.

#130 Add integration test support
  UPGRADE.md
  application/overlay/Jenkinsfile.twig
  application/skeleton/integration/helper_test.go
  docs/README.md
  docs/how-to-guides/write-integration-tests.md
  harness/config/commands.yml
  harness/config/confd.yml
  harness/scripts/integration/run.sh.twig
Labels: enhancement

#132 Add note to UPGRADE.md for kafka.host attribute
  UPGRADE.md
Labels: skip-changelog

#134 Update changelog for 0.10.0 release
  CHANGELOG.md
Labels: skip-changelog

#135 Quote environment variables in integration/run.sh
  harness/scripts/integration/run.sh.twig
Labels: bug

#136 Use php escapeshellarg for escaping data inserted into bash scripts
  harness/config/functions.yml
  harness/scripts/integration/run.sh.twig
Labels: bug

#137 Pass environment variables to all host integration test commands
  harness/config/commands.yml
  harness/config/confd.yml
  harness/scripts/integration/run-one.sh.twig
  harness/scripts/integration/run.sh.twig
Labels: bug

#140 Fix location of enableServiceLinks
  helm/app/templates/application/app/deployment.yaml
Labels: bug

#141 Quote sub-shell output in 'ws go docker fmt check'
  harness/config/commands.yml
Labels: bug
