Repository inviqa/harness-go, pull requests merged in 2021-12, with the labels that each got.

#198 Fix the github token inclusion
  harness/attributes/common.yml
Labels: bug

#201 Set buildkit env vars for ws recompile
  harness/config/commands.yml
Labels: bug

#199 Automatically create a dedicated test database for Postgres
  _twig/docker-compose.yml/service/postgres.yml.twig
  docker/image/postgres/Dockerfile.twig
  docker/image/postgres/create-test-database.sql.twig
  docs/how-to-guides/add-a-database.md
  harness/config/confd.yml
Labels: enhancement

#196 Use a volume mount by default to run everything in docker
  UPGRADE.md
  _twig/docker-compose.yml/application.yml.twig
  application/overlay/Jenkinsfile.twig
  docs/README.md
  docs/development-and-production.md
  docs/harness-attributes.md
  harness/attributes/common.yml
  harness/config/commands.yml
  harness/config/confd.yml
  harness/scripts/docker/compose-exec.sh
  harness/scripts/integration/host-run.sh.twig
  harness/scripts/integration/run-one.sh.twig
  harness/scripts/integration/run.sh
  harness/scripts/integration/run.sh.twig
Labels: breaking-change
