Repository inviqa/harness-go, pull requests merged in 2021-11, with the labels that each got.

#172 Correctly detect CI env in 'external-images pull' command
  harness/config/external-images.yml
Labels: bug

#173 Switch Kafka and Zookeeper images to bitnami variants
  UPGRADE.md
  _twig/docker-compose.yml/service/kafka.yml.twig
  harness/attributes/common.yml
Labels: enhancement

#174 Wait longer in CI for containers to start before verifying
  _twig/docker-compose.yml/service/kafka.yml.twig
  test
Labels: bug

#175 Add option to copy additional arbitrary files to production image
  .ci/1.17/production/.build-prod
  docker/image/app/include/Dockerfile.prod.twig
  docs/harness-attributes.md
  harness/attributes/common.yml
  harness/config/functions.yml
Labels: enhancement

#177 Bump docker-compose.yml version to 3.7
  docker-compose.yml.twig
Labels: bug

#187 Make it easier to use inviqa/kafka-outbox-relay
  _twig/docker-compose.yml/service/kafka-outbox-relay.yml.twig
  docs/how-to-guides/add-a-database.md
  docs/how-to-guides/add-kafka-outbox-relay.md
  docs/how-to-guides/add-kafka.md
  harness/attributes/docker.yml
Labels: enhancement

#189 Fix broken MySQL image attribute in docker.yml
  harness/attributes/docker.yml
Labels: bug, skip-changelog

#192 Provide GOOS/GOARCH by default
  docker/image/app/include/Dockerfile.base.twig
Labels: bug

#193 Set --builder when publishing multiplatform image
  harness/scripts/docker/publish.sh.twig
Labels: bug, skip-changelog
